### ISSUE TITLE
Prevent from adding content and additional data 

### ISSUE THREAD

**Issue by schotman** [sachatrauwaen/OpenContent#109] opened 2020-01-14 09:57 UTC
Use case:
Data: list of items with categories
Templates: List & Latest

The idea is that content managers in a derived module, for example a latest template or a category template, do not have the option to add additional data or content.

With additional data I have already experienced that people thought this was a filter and therefore deleted all categories except the one they wanted to keep ...

![image](https://user-images.githubusercontent.com/2582737/72333718-8c129100-36bc-11ea-8e31-171ea3d62dcc.png)

So in the manifest the option to disable the add and additionalData buttons

**Comment by Timo-Breumelhof** [comment] 2020-11-12 14:11
Duplicate of #135

**Closed by Timo-Breumelhof** 2020-11-12 14:11 UTC
Labels: enhancement
